/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WeCheckbox {
        "checked": boolean;
        "disabled": boolean;
        "onChange": any;
        "value": string;
    }
    interface WeRadio {
        "checked": boolean;
        "disabled": boolean;
        "value": string;
    }
}
declare global {
    interface HTMLWeCheckboxElement extends Components.WeCheckbox, HTMLStencilElement {
    }
    var HTMLWeCheckboxElement: {
        prototype: HTMLWeCheckboxElement;
        new (): HTMLWeCheckboxElement;
    };
    interface HTMLWeRadioElement extends Components.WeRadio, HTMLStencilElement {
    }
    var HTMLWeRadioElement: {
        prototype: HTMLWeRadioElement;
        new (): HTMLWeRadioElement;
    };
    interface HTMLElementTagNameMap {
        "we-checkbox": HTMLWeCheckboxElement;
        "we-radio": HTMLWeRadioElement;
    }
}
declare namespace LocalJSX {
    interface WeCheckbox {
        "checked"?: boolean;
        "disabled"?: boolean;
        "onChange"?: any;
        "value": string;
    }
    interface WeRadio {
        "checked"?: boolean;
        "disabled"?: boolean;
        "value": string;
    }
    interface IntrinsicElements {
        "we-checkbox": WeCheckbox;
        "we-radio": WeRadio;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "we-checkbox": LocalJSX.WeCheckbox & JSXBase.HTMLAttributes<HTMLWeCheckboxElement>;
            "we-radio": LocalJSX.WeRadio & JSXBase.HTMLAttributes<HTMLWeRadioElement>;
        }
    }
}
